name: a2c
policy: MlpPolicy
learning_rate: 0.0007
n_steps: 5
gamma: 0.99
gae_lambda: 1.0
ent_coef: 0.0
vf_coef: 0.5
total_timesteps: 100000
evaluation_episodes: 50
eval_freq: 5000
seed: 11
policy_kwargs:
  net_arch: [128, 128]
